### ISSUE TITLE
UI for creating conversation?

### ISSUE THREAD

**Issue by rahul-thakoor** [smooch/smooch-bot-example#13]
Hello. I am able to use the chatbot. Now, I need to setup the conversation, and I find doing it by code a bit counterproductive. Is there an easier way to do this? like here [EstherBot](https://github.com/esthercrawford/EstherBot)

**Comment by alavers** [comment]
The script.json approach that EstherBot uses makes it easy to build simple bot scripts, but it's limited. You can't do fancier things such as fetching info from external services, or automating actions based on user input. For that you need to write code.

But if a simple script like what EstherBot provides is all you need, I suppose a bot creation UI would be neat, but out of scope for this project.
