### ISSUE TITLE
smooch-bot not replying

### ISSUE THREAD

**Issue by user-359** [smooch/smooch-bot-example#15]
Hi,
I tried setting up smooch-bot via the Heroku example.  I open the heroku app and chat with the bot, but I don't receive any replies.  The messages I type are being forwarded to smooch because I am receiving email notifications...but no replies from smooch-bot in the chat window.

I am not a programmer and try to follow the directions.  I am deploying the app via dropbox connection. Is it normal that the Heroku folder in my dropbox is empty?  I tried to uploading script.js into Dropbox>Apps>Heroku and Dropbox>Apps>Heroku>mybot...but no replies.  I am not sure where I went wrong, could you help me point in the right direction?

Thank you for your help in advance!

**Comment by jwc911037** [comment]
Hi, @user-359. Did you solve this problem? I have the same problem with you. The only difference is that I connected with GitHub on Heroku, not Dropbox. The script.js does not work.
