### ISSUE TITLE
bot.SetProp() inconsistently works

### ISSUE THREAD

**Issue by nacharya114** [smooch/smooch-bot-example#16]
Whenever I use bot.setProp in my Script, it inconsistently saves the properties I use. It is necessary to retain certain values in the Smooch Store for my bot, but it is also essential that I clear them out after I use them. When I try to clear them with bot.setProp('property', ""), it only clears out certain properties while other retain their value.

**Comment by alavers** [comment]
https://github.com/smooch/smooch-bot/issues/6
