### ISSUE TITLE
Reply button in web embedded widget opens new browser tab on click

### ISSUE THREAD

**Issue by daveroma** [smooch/smooch-bot-example#20]
I'm outputting a "Reply Button" to the conversation using the following code:

```
getRole: {
    prompt: (bot) => bot.say(`What's your primary role at your company? %[Agent](reply:agent) %[Team Manager](reply:team) %[Broker](reply:broker)`),
    receive: (bot, message) => {
        return bot.setProp('role', message.text)
            .then(() => bot.say(`Thanks!`))
            .then(() => 'getBusinessType');
    }
},
```

When one of the Reply buttons is clicked a new browser tab opens instead of the reply value being added to the conversation. After inspecting the DOM I noticed the Reply buttons are actually being output as anchors with `target="_blank"`.

**Comment by mspensieri** [comment]
Reply buttons are not yet supported on our SDKs: http://docs.smooch.io/ios/#replies

> Reply buttons are currently supported on Facebook Messenger, LINE, WeChat, Telegram, SMS, and Email Messaging.

**Comment by daveroma** [comment]
@mspensieri thanks, so would a postback be a good option for mimicking the behavior of suggested replies in a custom web embedded widget?

**Comment by mspensieri** [comment]
Yes, postbacks are a good alternative. I think the smoochbot project was created before postbacks were supported in Smooch though, so I'm not sure if this library handles those actions or not with the current code. @alavers ?

**Comment by alavers** [comment]
Yessir. Bam --> https://github.com/smooch/smooch-bot-example/blob/e515583ff09b7baaf1ae3362145db8d638d92f37/heroku/index.js#L109
