### ISSUE TITLE
Restarting the bot conversation

### ISSUE THREAD

**Issue by daveroma** [smooch/smooch-bot-example#21]
I cloned this repo and am building a bot which is running in a web embedded widget. Since I'm in development mode, I need a way to explicitly call `start` in the `script.js` as a way to "restart" my bot script when I add or change functionality.

Is there a way I can control calling the `start` `prompt` method programmatically?

```
start: {
    prompt: (bot) => {
        return bot.say(`Hey, I'm a robot! Just going to ask you a few questions before you get started...`)
            .then(bot.say(`First up: what's your full name?`))
    },
    receive: function (bot, message) {
        const name = message.text;
        const firstName = name.split(' ').slice(0, -1).join(' ');
        return bot.setProp('name', name)
            .then(() => bot.say(`Nice to meet you ${firstName}!`))
            .then(() => 'getRole');
    }
},
```

**Comment by daveroma** [comment]
Welp, after trial and error I figured this out. If you want to "refresh" the conversation state (which is helpful, if not necessary while making changes to your bot during development) all you have to do is init smooch without a userId. The conversation state will still persist to local storage and if you want to completely "refresh" the convo just load your dev URL in a new incognito window.

**Comment by alavers** [comment]
To elaborate on this, you can transition a user to whatever script state you wish at any time via `stateMachine.setState()`.

You could for example introduce some kind of "reset" keyword, such that when the user says "reset" it brings them back to the beginning of the script. You could parse for such incoming messages in `handleMessages` for example: https://github.com/alavers/smooch-bot-example/blob/master/heroku/index.js#L83 and
