### ISSUE TITLE
smooch Bot /help menu implementation

### ISSUE THREAD

**Issue by qadir-genetech** [smooch/smooch-bot-example#25]
Can we implement bot /help menu in using smooch

See image below for example in telegram
![telegram chat](https://cloud.githubusercontent.com/assets/14326497/18078474/1dbe87dc-6ea5-11e6-8a3b-9561b7c53c80.png)

Is this possible? Please suggest me any pointers and directions for this.

How this work?
User typed "/" bot will show the available help menu as a autocomplete menu

**Comment by alavers** [comment]
https://core.telegram.org/bots#commands

You can specify a list of suggested commands for your bot by saying `/setcommands` to the Botfather.

Telegram receives user commands as raw text, and so too will Smooch. So to have smooch-bot handle incoming commands, you would parse and react to them inside `handleMessage`.

**Comment by qadir-genetech** [comment]
but this will only work in telegram and Smooch. right? but what about the others like facebook, Line  etc

**Comment by alavers** [comment]
As far as I know facebook and line don't handle forward slash style /commands the same way telegram does, eg you can't have the fancy popup with command suggestions.

But you could configure your bot to spit out the list of commands in response to `/help`. It's all text in and text out, so you can pretty much do whatever you like. Just parse the incoming message accordingly in `handleMessage`.

**Comment by qadir-genetech** [comment]
Wow! that make sense. thanks for the idea
