### ISSUE TITLE
how to get last bot state

### ISSUE THREAD

**Issue by qadir-genetech** [smooch/smooch-bot-example#30]
Hello,

Is there any way to get the last state executed by the bot. Like 

let say I have states defined for my bot are given below. 

```
ASK_NAME:
ASK_EMAIL:
ASK_ADDRESS:
```

ASK_NAME executed successfully then bot is on ASK_EMAIL state, Can I get the last executed state was ASK_NAME, is there any way to get this?

Regards
Qadir Hussain

**Comment by alavers** [comment]
Hmm yeah it might be useful to track a history of past state transitions, both for debugging and for complex bot behaviors.

In short, this is not currently supported but I can make some suggestions as to how it could or should be done:

One caveat is that storing such an ever-growing list of states in `SmoochMemoryStore` would be a bad idea, it is only designed to store user props as simple key value pairs, and there are field size limits.

It would make more sense to swap out `SmoochMemoryStore` with an implementation backed by a dedicated database. A redis list might be a good fit for storing state history perhaps.

**Comment by qadir-genetech** [comment]
OK. thanks for the information. Do you have any plan to do this nearly.

**Comment by alavers** [comment]
No, I'm not actively working on this project.
