### ISSUE TITLE
Get message from slack/frontApp and do some processing!

### ISSUE THREAD

**Issue by qadir-genetech** [smooch/smooch-bot-example#31]
Hi there!

Sorry for the bad title, Let me explain.

First thing to tell you is We have configured Slack as my Receiving channel (business end, Later we will configure the frontApp and many others).

We are developing our contact-us (live chat/ Support) page. We want both the Bot and Human agent can answer our customer's queries. Human should answer the queries which a bot is unable to understand. We have done this already by using the `bot.setProp('silent', true)`. Whenever our customer asks a query, we first check it either it can be handled by our bot (with certain AI) or not. IFF yes then bot will simply answer the query. IFF not we redirect our customer to our live human agent by simply setting the `bot.setProp('silent', true)`.

Now here comes the climax. Now bot is Turned OFF and our Human Agent (on Slack) is chatting with our customer live. Now If customer asks an query which can be handled by our bot, Is there any way that our Human Agent (on slack) can turn the bot ON by simply setting `bot.setProp('silent', false)`.

**QUESTION IN SHORT**: 
Is there any way to process the messages from Slack/FrontApp (or any business end). So that we can turn the Bot ON.

**Comment by mspensieri** [comment]
If you configure your Smooch webhook with the `message:appMaker` trigger, then your bot will be able to process messages received from Slack or Front. Your bot should make sure to check the `role` of the message to know whether it was sent by the user, or a member of your team before deciding how to handle the message.

**Comment by qadirsuh** [comment]
Thanks for response. Where I can get this configuration in smooch?

**Comment by qadir-genetech** [comment]
I did it. Thanks for pointing this out. 
here What I did in heroku/index.js
```
app.post('/slack', function(req, res, next) {

    const trigger = req.body.trigger;

    switch (trigger) {
        case 'message:appMaker':
            console.log('message:appMaker');
            handleBusinessMessages(req, res);
            break;

        default:
            console.log('Ignoring unknown webhook trigger: /slack', trigger);
    }
});
```
in smooch configuration
https://www.dropbox.com/s/6hqaalmau0na3gh/Screenshot%202017-01-10%2015.27.46.png?dl=0

Now I can pass the message from the slack/front through my code. BUT

Can we control this i.e . The message (from slack/front) should not be displayed/rendered to our customer unless we process it. Right now its got received to our customers immediately once we send it from slack/Front. Like is there any method `bot.say("bla bla bla")` i.e appMaker.say("bla bla") etc ;)

**Comment by mspensieri** [comment]
Any message you send through Slack/Front will be added to the conversation history (and visible by the user) - there isn't currently a way to prevent this behaviour

**Comment by qadir-genetech** [comment]
OK. thanks for this.

**Comment by qadir-genetech** [comment]
Is there currently a way to prevent this? In other words: Smooch as a reverse proxy would be very nice.
