### ISSUE TITLE
How to deploy this to existing heroku app.

### ISSUE THREAD

**Issue by qadir-genetech** [smooch/smooch-bot-example#32]
Hi there.

I want to deploy the Smooch bot on my heroku to my existing heroku app.
using the deploy button provided i.e https://heroku.com/deploy?template=https://github.com/smooch/smooch-bot-example
but its asking me to create the new heroku app.
https://www.dropbox.com/s/8xe1h56jogo24ox/Screenshot%202017-01-11%2021.03.58.png?dl=0
how can I deploy it to my existing heroku app.

Or can you guide me how can I do this manually?

**Comment by alavers** [comment]
Heroku has comprehensive and fantastic docs: https://devcenter.heroku.com/categories/nodejs
