### ISSUE TITLE
Cannot send message to our customer when customer did not write first. :(

### ISSUE THREAD

**Issue by qadir-genetech** [smooch/smooch-bot-example#36]
let say we have a customer using our iOS app (smooch iOS SDK is integrated) but he/she didn't sent a message via smooch chat widget (or via any other messaging channel). is there any way to know that new customer has started using our app, so that we can start conversation with them by sending her a message saying greetings

basically the question is How to send a message (smooch) to our customer initiated by us via slack and/or front?

Fred said this on Smooch support
`Hi there! Starting a conversation with a user will only work with whispers. We don’t offer a way to start conversation through business systems since it would require we create channels for every init in your app (it would be too heavy for you to handle)`

**But**

Whispers will initiate the chat with the customer once he/she send us reply. If he/she didn't replied back we can't init the chat with our customer. And that's why whispers will fail in this situation too.

We do need a way to start conversation with our customers through business systems anyhow. we can handle all that heavy stuff.
_Please give any suggestion/direction or any hack to to this. Thanks_

Can we do this something like using slack api? like what happens when a new user send us a message? A new channel is created and a user joins that channel. right?

I have successfully created a channel in slack via slack api. here is the code.

https://www.dropbox.com/s/r27fd6t8pii2qip/Screenshot%202017-03-27%2013.54.54.png?dl=0

**Comment by alavers** [comment]
You don't need to wait for the user to send a message to trigger a whisper. You can trigger one via the track event API for example: https://docs.smooch.io/rest/#track-event

Is that what you were looking for?

**Comment by qadir-genetech** [comment]
Recalling the scenario.


let say we have a customer using our iOS app (smooch iOS SDK is integrated) but he/she didn't sent a message via smooch chat widget (or via any other messaging channel). is there any way to know that new customer has started using our app, so that we can start conversation with them by sending him/her a message (Not predefined message via whisper)

The question is How to send a message to our customer (already using our app/smooch is integrated) initiated by us via slack and/or front?

**Comment by alavers** [comment]
The customer (or your code) needs to initiate a conversation by sending a message before they'll show up in Slack or Front.

**Comment by qadir-genetech** [comment]
But we wan't to send our customers first message. can we achieve this in any way?

**Comment by alavers** [comment]
Yes. You can [pre-create](https://docs.smooch.io/rest/#pre-create-app-user) the user and then [issue them a JWT](https://docs.smooch.io/guide/authenticating-users/).
