### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by assafweinberg** [smooch/smooch-bot-example#5]
More of a question than an issue. When you create an action button like

```
%[Button Text](postback:button action)
```

How do you specify the handler for the postback. What does "button action" map to? Can you show an example?

**Comment by alavers** [comment]
The payload is delivered by way of a smooch webhook, so you'll need to have some webservice running to catch the event.

More details here: http://docs.smooch.io/rest/#webhooks
And here: http://docs.smooch.io/ios/#postbacks
